pics:
    resource: Picta\Controller\PicsController
    type:     rest
app:
    resource: "@Picta/Controller/DefaultController.php"
    type:     annotation
api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional

api_login_check:
    path: /api/login_check